// Generated by risc0_build::embed_methods() at build time (see build.rs).
// Exposes:
//   ZKVAULT_GUEST_ELF: &[u8]   -- the compiled guest binary, fed to the prover
//   ZKVAULT_GUEST_ID:  [u32; 8] -- the "image ID", a hash of the guest binary
//                                  that the verifier checks the receipt against.
//                                  This is the value your deployed contract
//                                  must be initialized with.
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
